pipeline {
    agent {
        docker {
            image 'orxe-component-agent:snapshot-v0.01' 
        }
    }
    stages {
        stage('Build') {
            steps {
                
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}